### ISSUE TITLE
CSRF error

### ISSUE THREAD

**Issue by framawiki** [lucaswerkmeister/tool-speedpatrolling#2]
Hi, very interesting tool!
It currently fails when I click on any of the buttons with `CSRF error` message, like on https://tools.wmflabs.org/speedpatrolling/diff/856041005/skip.

**Comment by lucaswerkmeister** [comment]
Hm, I’m not sure why this would happen… can you try it out again?

**Comment by framawiki** [comment]
Hello, I don't have the problem anymore. It must have come from my browser. Sorry for the inconvenience.
